// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDocTAhHYl7e9-h1FtWjKEAeoMUTDGjDu8',
    appId: '1:572988565147:android:d784846623fea5b795083e',
    messagingSenderId: '572988565147',
    projectId: 'joxmako-b7ec4',
    databaseURL: 'https://joxmako-b7ec4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'joxmako-b7ec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc7N0gm-Gg1fLeVGDCnxEDUTG0cTkSmcM',
    appId: '1:572988565147:ios:48b598d6babd2eb495083e',
    messagingSenderId: '572988565147',
    projectId: 'joxmako-b7ec4',
    databaseURL: 'https://joxmako-b7ec4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'joxmako-b7ec4.firebasestorage.app',
    androidClientId: '572988565147-9325jsvae7sssvi2ig7lnqv26kdobk2t.apps.googleusercontent.com',
    iosClientId: '572988565147-tbre7mpqhjhtk8uiapc349rv8e2k0hnn.apps.googleusercontent.com',
    iosBundleId: 'com.joxmako.driver',
  );
}